---
# Default prefixes of Bastion. This is permanent, i.e., once set, it'll stay
# the same until the database is reset.
# Although, you can use the `prefix` command to change server speific prefix.
prefixes:
  - "!"
  - "*"

# Default Presence of Bastion
presence:
  # Default status of Bastion.
  # Valid values are `online`, `idle`, `dnd` and `invisible`
  status: "dnd"
  # Default activity of Bastion
  activity:
    # Activity type.
    # Valid values are `PLAYING`, `LISTENING`, `WATCHING` and `STREAMING`.
    # Note that `STREAMING` activity will only work if a valid Twitch channel URL
    # is added in the `url` field below.
    type: "PLAYING"
    # Activity name.
    # The name of the activity.
    name: "with Ganymede"
    # Acitvity URL
    # Twitch channel URL for `STREAMING` activity.
    url: "https://twitch.tv/k3rn31p4nic"
